spring.application.name=avenzo

spring.datasource.url=jdbc:postgresql://localhost:5432/my_postgres_db
spring.datasource.username=admin
spring.datasource.password=p_admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Keeps your database schema synced with your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update

# create new db data each time
#spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

jwt.secret=k37fQaSVeXFjtEogmUbbFsWoGmA9fzssmXaV8dk5wY6Dz5LMktXrAJWdrxapY5oWhFYddtkgMxUTX3eoBd7tSz


# /api-docs endpoint custom path
#springdoc.api-docs.path=/docs
#springdoc.api-docs.path=/openapi.json
springdoc.api-docs.path=/docs/openapi.json
